"""Configuration settings for Football ELO Odds Calculator."""
from pathlib import Path
from typing import Dict, List, Tuple

# File paths
DATA_DIR = Path(__file__).resolve().parent / "data"
LEAGUE_STATS_PATH = DATA_DIR / "league_stats.json"
ODDS_ICON_PATH = Path(__file__).resolve().parent / "odds_icon.png"
STYLE_CSS_PATH = Path(__file__).resolve().parent / "style.css"

# UI Configuration
SPINNER_MESSAGES = [
    "Fetching the latest football ratings...",
    "Hold tight, we're gathering the data...",
    "Just a moment, crunching the numbers...",
    "Loading the football magic...",
    "Almost there, preparing the stats...",
]

# HTTP Request Configuration
BASE_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache",
}

# Statistical Model Configuration
DEFAULT_DRAW_RATE = 0.27
DEFAULT_AVG_GOALS = 2.6

# Optional weight for blending the observed league draw rate back into the
# Poisson-derived draw probability. Default keeps the Poisson result.
DRAW_OBS_WEIGHT = 0.0

# Global multiplier applied to the Bradley-Terry draw ratio. Values above 1
# lift draw probabilities (default bumps them ~10%), values below 1 trim them.
DRAW_RATE_SCALE = 1.1

# Elo-based scaling parameters for adjusting the expected goal total before
# computing the Poisson draw probability. The factor is applied to the rating
# gap (normalised by the divisor) and capped to avoid extreme totals.
ELO_GOAL_SCALE_FACTOR = 0.35
ELO_GOAL_SCALE_DIVISOR = 400
ELO_GOAL_SCALE_CAP = 0.6

# League Mapping ("Rosetta Stone")
# Maps (country_key, league_code) from leagues_data to the string key in the loaded stats
LEAGUE_STATS_MAP: Dict[Tuple[str, str], str] = {
    ("Albania", "AL1"): "Albania - Abissnet Superiore",
    ("Andorra", "AD1"): "Andorra - Primera Divisio",
    ("Argentina", "AR1"): "Argentina - Liga Profesional - Apertura",
    ("Argentina", "AR2"): "Argentina - Primera B - Apertura",
    ("Armenia", "AM1"): "Armenia - Premier League",
    ("Australia", "AU1"): "Australia - A-League",
    ("Australia", "AU2V"): "Australia - NPL Victoria",
    ("Australia", "AU2NSW"): "Australia - NPL New South Wales",
    ("Australia", "AU2S"): "Australia - NPL South Australia",
    ("Australia", "AU2W"): "Australia - NPL Western Australia",
    ("Australia-Women", "AW1"): "Australia - A-League Women",
    ("Austria", "AT1"): "Austria - Bundesliga",
    ("Austria", "AT2"): "Austria - 2. Liga",
    ("Austria", "AT3W"): "Austria - Regionalliga West",
    ("Austria", "AT3M"): "Austria - Regionalliga Mitte",
    ("Austria", "AT3O"): "Austria - Regionalliga Ost",
    ("Austria-Women", "AW1"): "Austria - Bundesliga Women",
    ("Azerbaijan", "AZ1"): "Azerbaijan - Premier League",
    ("Bahrain", "BH1"): "Bahrain - Premier League",
    ("Bangladesh", "BD1"): "Bangladesh - Premier League",
    ("Belarus", "BY1"): "Belarus - Vysshaya Liga",
    ("Belgium", "BE1"): "Belgium - Pro League",
    ("Belgium", "BE2"): "Belgium - Challenger Pro League",
    ("Bolivia", "BO1"): "Bolivia - Division Profesional",
    ("Bosnia-Herzegovina", "BA1"): "Bosnia and Herzegovina - Premier Liga",
    ("Brazil", "BR1"): "Brazil - Serie A",
    ("Brazil", "BR2"): "Brazil - Serie B",
    ("Brazil", "BR3"): "Brazil - Serie C",
    ("Brazil", "BRC"): "Brazil - Carioca",
    ("Brazil", "BRGA"): "Brazil - Gaucho",
    ("Brazil-Women", "FB1"): "Brazil - Brasileiro Women",
    ("Bulgaria", "BG1"): "Bulgaria - Parva Liga",
    ("Bulgaria", "BG2"): "Bulgaria - Vtora Liga",
    ("Canada", "CA1"): "Canada - Premier League",
    ("Chile", "CL1"): "Chile - Liga de Primera",
    ("Chile", "CL2"): "Chile - Liga de Ascenso",
    ("China", "CN1"): "China - Super League",
    ("China", "CN2"): "China - League One",
    ("China", "CN3"): "China - League Two",
    ("Colombia", "CO1"): "Colombia - Primera A - Apertura",
    ("Colombia", "CO2"): "Colombia - Primera B - Apertura",
    ("Costa-Rica", "CR1"): "Costa Rica - Primera Div. - Apertura",
    ("Croatia", "HR1"): "Croatia - 1. HNL",
    ("Croatia", "HR2"): "Croatia - 1. NL",
    ("Cyprus", "CY1"): "Cyprus - Cyprus League",
    ("Cyprus", "CY2"): "Cyprus - Division 2",
    ("Czech-Republic", "CZ1"): "Czech Republic - 1. Liga",
    ("Czech-Republic", "CZ2"): "Czech Republic - FNL",
    ("Czech-Republic-Women", "LZ1"): "Czech Republic - 1. Liga Women",
    ("Denmark", "DK1"): "Denmark - Superligaen",
    ("Denmark", "DK2"): "Denmark - 1st Division",
    ("Denmark", "DK3"): "Denmark - 2nd Division",
    ("Ecuador", "EC1"): "Ecuador - Liga Pro",
    ("Egypt", "EG1"): "Egypt - Premier League",
    ("England", "UK1"): "England - Premier League",
    ("England", "UK2"): "England - Championship",
    ("England", "UK3"): "England - League One",
    ("England", "UK4"): "England - League Two",
    ("England", "UK5"): "England - National League",
    ("England", "UK6N"): "England - National L. North",
    ("England", "UK6S"): "England - National L. South",
    ("England-Women", "UW1"): "England - Women Super League",
    ("England-Women", "UW2"): "England - WSL 2",
    ("Estonia", "EE1"): "Estonia - Meistriliiga",
    ("Färöer", "FA1"): "FaroeIslands - Premier League",
    ("Finland", "FI1"): "Finland - Veikkausliiga",
    ("Finland", "FI2"): "Finland - Ykkosliga",
    ("Finland", "FI3"): "Finland - Ykkonen",
    ("Finland", "FI4A"): "Finland - Kakkonen Group A",
    ("Finland", "FI4B"): "Finland - Kakkonen Group B",
    ("Finland", "FI4C"): "Finland - Kakkonen Group C",
    ("Finland-Women", "FW1"): "Finland - Kansallinen Liiga Women",
    ("France", "FR1"): "France - Ligue 1",
    ("France", "FR2"): "France - Ligue 2",
    ("France", "FR3"): "France - National",
    ("France-Women", "FF1"): "France - Premiere Ligue Women",
    ("Georgia", "GE1"): "Georgia - Erovnuli Liga",
    ("Georgia", "GE2"): "Georgia - Erovnuli Liga 2",
    ("Germany", "DE1"): "Germany - Bundesliga",
    ("Germany", "DE2"): "Germany - 2. Bundesliga",
    ("Germany", "DE3"): "Germany - 3. Liga",
    ("Germany", "DE4N"): "Germany - Regionalliga Nord",
    ("Germany", "DE4NO"): "Germany - Regionalliga Nordost",
    ("Germany", "DE4W"): "Germany - Regionalliga West",
    ("Germany", "DE4SW"): "Germany - Regionalliga Sudwest",
    ("Germany", "DE4B"): "Germany - Regionalliga Bayern",
    ("Germany-Women", "GW1"): "Germany - Bundesliga Women",
    ("Germany-Women", "GW2"): "Germany - 2. Bundesliga Women",
    ("Gibraltar", "GI1"): "Gibraltar - Premier Division",
    ("Greece", "GR1"): "Greece - Super League",
    ("Guatemala", "GT1"): "Guatemala - Liga Nacional - Apertura",
    ("Hong Kong", "HK1"): "Hong Kong - Premier League",
    ("Hungary", "HU1"): "Hungary - NB I",
    ("Hungary", "HU2"): "Hungary - NB II",
    ("Iceland", "IS1"): "Iceland - Besta deild",
    ("Iceland", "IS2"): "Iceland - 1. Deild",
    ("Iceland", "IS3"): "Iceland - 2. Deild",
    ("Iceland-Women", "IW1"): "Iceland - Besta deild Women",
    ("India", "IN1"): "India - Super League",
    ("India", "IN2"): "India - I-League",
    ("Indonesia", "ID1"): "Indonesia - Liga 1",
    ("Iran", "IA1"): "Iran - Pro League",
    ("Ireland", "IR1"): "Ireland - Premier Division",
    ("Ireland", "IR2"): "Ireland - First Division",
    ("Israel", "IL1"): "Israel - Ligat HaAl",
    ("Italy", "IT1"): "Italy - Serie A",
    ("Italy", "IT2"): "Italy - Serie B",
    ("Italy", "IT3A"): "Italy - Serie C - Group A",
    ("Italy", "IT3B"): "Italy - Serie C - Group B",
    ("Italy", "IT3C"): "Italy - Serie C - Group C",
    ("Italy-Women", "IF1"): "Italy - Serie A Women",
    ("Jamaica", "JM1"): "Jamaica - Premier League",
    ("Japan", "JP1"): "Japan - J1 League",
    ("Japan", "JP2"): "Japan - J2 League",
    ("Japan", "JP3"): "Japan - J3 League",
    ("Japan-Women", "JW1"): "Japan - WE League",
    ("Japan-Women", "JW2"): "Japan - Nadeshiko League 1",
    ("Jordan", "JO1"): "Jordan - Premier League",
    ("Kazakhstan", "KZ1"): "Kazakhstan - Premier League",
    ("Kuwait", "KW1"): "Kuwait - Premier League",
    ("Latvia", "LA1"): "Latvia - Virsliga",
    ("Latvia", "LA2"): "Latvia - 1. Liga",
    ("Lithuania", "LT1"): "Lithuania - A Lyga",
    ("Lithuania", "LT2"): "Lithuania - 1st League",
    ("Malaysia", "MY1"): "Malaysia - Super League",
    ("Mexico", "MX1"): "Mexico - Liga MX - Apertura",
    ("Mexico-Women", "MF1"): "Mexico - Liga MX - Apertura",
    ("Moldova", "MD1"): "Moldova - Divizia Nationala",
    ("Montenegro", "MN1"): "Montenegro - First League",
    ("Morocco", "MA1"): "Morocco - Botola Pro",
    ("Netherlands", "NL1"): "Netherlands - Eredivisie",
    ("Netherlands", "NL2"): "Netherlands - Eerste Divisie",
    ("Netherlands", "NL3"): "Netherlands - Tweede Divisie",
    ("Netherlands-Women", "NV1"): "Netherlands - Eredivisie Women",
    ("Northern-Ireland", "NI1"): "Northern Ireland - NIFL Premiership",
    ("Northern-Ireland", "NI2"): "Northern Ireland - NIFL Championship",
    ("North-Macedonia", "MK1"): "North Macedonia - First League",
    ("Norway", "NO1"): "Norway - Eliteserien",
    ("Norway", "NO2"): "Norway - 1st Division",
    ("Norway", "NO3G1"): "Norway - Division 2 - Gr. 1",
    ("Norway", "NO3G2"): "Norway - Division 2 - Gr. 2",
    ("Norway-Women", "NW1"): "Norway - Toppserien Women",
    ("Norway-Women", "NW2"): "Norway - 1. Division Women",
    ("Paraguay", "PY1"): "Paraguay - Primera Div. - Apertura",
    ("Peru", "PE1"): "Peru - Liga 1 - Apertura",
    ("Poland", "PL1"): "Poland - Ekstraklasa",
    ("Poland", "PL2"): "Poland - 1. Liga",
    ("Poland", "PL3"): "Poland - 2. Liga",
    ("Portugal", "PT1"): "Portugal - Liga Portugal",
    ("Portugal", "PT2"): "Portugal - Liga Portugal 2",
    ("Portugal", "PT3"): "Portugal - Liga 3",
    ("Qatar", "QA1"): "Qatar - Stars League",
    ("Qatar", "QA2"): "Qatar - Division 2",
    ("Romania", "RO1"): "Romania - Liga 1",
    ("Romania", "RO2"): "Romania - Liga 2",
    ("Russia", "RU1"): "Russia - Premier League",
    ("Russia", "RU2"): "Russia - FNL",
    ("Rwanda", "RW1"): "Rwanda - Premier League",
    ("San-Marino", "SM1"): "SanMarino - Campionato Sammarinese",
    ("Saudi-Arabia", "SA1"): "Saudi Arabia - Professional League",
    ("Saudi-Arabia", "SA2"): "Saudi Arabia - Division 1",
    ("Scotland", "SC1"): "Scotland - Premiership",
    ("Scotland", "SC2"): "Scotland - Championship",
    ("Scotland", "SC3"): "Scotland - League One",
    ("Scotland", "SC4"): "Scotland - League Two",
    ("Scotland-Women", "SP1"): "Scotland - SWPL 1 Women",
    ("Serbia", "CS1"): "Serbia - Super Liga",
    ("Serbia", "CS2"): "Serbia - Prva Liga",
    ("Singapore", "SG1"): "Singapore - Premier League",
    ("Slovakia", "SK1"): "Slovakia - 1. Liga",
    ("Slovakia", "SK2"): "Slovakia - 2. Liga",
    ("Slovenia", "SI1"): "Slovenia - Prva Liga",
    ("South-Africa", "ZA1"): "South Africa - Premier Division",
    ("South-Africa", "ZA2"): "South Africa - First Division",
    ("South-Korea", "KR1"): "South Korea - K League 1",
    ("South-Korea", "KR2"): "South Korea - K League 2",
    ("South-Korea-Women", "KX1"): "South Korea - WK League Women",
    ("Spain", "ES1"): "Spain - LaLiga",
    ("Spain", "ES2"): "Spain - LaLiga2",
    ("Spain-Women", "EW1"): "Spain - Liga F Women",
    ("Spain-Women", "EW2"): "Spain - Primera F. Women",
    ("Sweden", "SW1"): "Sweden - Allsvenskan",
    ("Sweden", "SW2"): "Sweden - Superettan",
    ("Sweden", "SW3N"): "Sweden - Div 1 - Norra",
    ("Sweden", "SW3S"): "Sweden - Div 1 - Sodra",
    ("Sweden-Women", "SX1"): "Sweden - Allsvenskan Women",
    ("Sweden-Women", "SX2"): "Sweden - Elitetan Women",
    ("Switzerland", "CH1"): "Switzerland - Super League",
    ("Switzerland", "CH2"): "Switzerland - Challenge League",
    ("Thailand", "TH1"): "Thailand - Thai League 1",
    ("Turkey", "TU1"): "Turkey - Super Lig",
    ("Turkey", "TU2"): "Turkey - 1. Lig",
    ("Turkey", "TU3B"): "Turkey - 2. Lig White Group",
    ("Turkey", "TU3K"): "Turkey - 2. Lig Red Group",
    ("UAE - Pro League", "AE1"): "UAE - Pro League",
    ("Ukraine", "UA1"): "Ukraine - Premier League",
    ("Ukraine", "UA2"): "Ukraine - Persha Liga",
    ("Uruguay", "UY1"): "Uruguay - Liga AUF Uruguaya - Apertura",
    ("Uruguay", "UY2"): "Uruguay - Liga AUF Uruguaya - Clausura",
    ("USA", "US1"): "USA - MLS",
    ("USA", "US2"): "USA - USL Championship",
    ("USA", "US3"): "USA - USL League One",
    ("USA-Women", "UV1"): "USA - NWSL",
    ("USA-Women", "UV2"): "USA - USL Super League",
    ("Venezuela", "VE1"): "Venezuela - Liga FUTVE - Apertura",
    ("Vietnam", "VN1"): "Vietnam - V League",
    ("Vietnam", "VN2"): "Vietnam - National League Women",
    ("Wales", "WL1"): "Wales - Cymru Premier",
}

# Combined dictionary for both Men's and Women's leagues
LEAGUES_DATA: Dict[str, Dict[str, List[str]]] = {
    "Men's": {
        "England": ["UK1", "UK2", "UK3", "UK4", "UK5", "UK6N", "UK6S"],
        "Germany": ["DE1", "DE2", "DE3", "DE4SW", "DE4W", "DE4N", "DE4NO", "DE4B"],
        "Italy": ["IT1", "IT2", "IT3C", "IT3B", "IT3A"],
        "Spain": ["ES1", "ES2"],
        "France": ["FR1", "FR2", "FR3"],
        "Sweden": ["SW1", "SW2", "SW3S", "SW3N"],
        "Netherlands": ["NL1", "NL2", "NL3"],
        "Russia": ["RU1", "RU2"],
        "Portugal": ["PT1", "PT2"],
        "Austria": ["AT1", "AT2", "AT3O", "AT3M", "AT3W"],
        "Denmark": ["DK1", "DK2", "DK3"],
        "Greece": ["GR1"],
        "Norway": ["NO1", "NO2", "NO3G1", "NO3G2"],
        "Czech Republic": ["CZ1", "CZ2"],
        "Turkey": ["TU1", "TU2", "TU3B", "TU3K"],
        "Belgium": ["BE1", "BE2"],
        "Scotland": ["SC1", "SC2", "SC3", "SC4"],
        "Switzerland": ["CH1", "CH2"],
        "Finland": ["FI1", "FI2", "FI3"],
        "Ukraine": ["UA1", "UA2"],
        "Romania": ["RO1", "RO2"],
        "Poland": ["PL1", "PL2", "PL3"],
        "Croatia": ["HR1", "HR2"],
        "Belarus": ["BY1"],
        "Israel": ["IL1"],
        "Iceland": ["IS1", "IS2", "IS3"],
        "Cyprus": ["CY1", "CY2"],
        "Serbia": ["CS1", "CS2"],
        "Bulgaria": ["BG1", "BG2"],
        "Slovakia": ["SK1", "SK2"],
        "Hungary": ["HU1", "HU2"],
        "Kazakhstan": ["KZ1"],
        "Bosnia-Herzegovina": ["BA1"],
        "Slovenia": ["SI1"],
        "Azerbaijan": ["AZ1"],
        "Ireland": ["IR1", "IR2"],
        "Latvia": ["LA1", "LA2"],
        "Georgia": ["GE1", "GE2"],
        "Albania": ["AL1"],
        "Lithuania": ["LT1", "LT2"],
        "North-Macedonia": ["MK1"],
        "Armenia": ["AM1"],
        "Estonia": ["EE1"],
        "Northern-Ireland": ["NI1", "NI2"],
        "Wales": ["WL1"],
        "Montenegro": ["MN1"],
        "Moldova": ["MD1"],
        "Färöer": ["FA1"],
        "Gibraltar": ["GI1"],
        "Andorra": ["AD1"],
        "San-Marino": ["SM1"],
        "Brazil": ["BR1", "BR2", "BR3", "BRC", "BRGA"],
        "Mexico": ["MX1"],
        "Argentina": ["AR1", "AR2"],
        "USA": ["US1", "US2", "US3"],
        "Colombia": ["CO1", "CO2"],
        "Ecuador": ["EC1"],
        "Paraguay": ["PY1"],
        "Chile": ["CL1", "CL2"],
        "Uruguay": ["UY1", "UY2"],
        "Costa-Rica": ["CR1"],
        "Bolivia": ["BO1"],
        "Guatemala": ["GT1"],
        "Venezuela": ["VE1"],
        "Peru": ["PE1"],
        "Jamaica": ["JM1"],
        "Canada": ["CA1"],
        "Japan": ["JP1", "JP2", "JP3"],
        "South-Korea": ["KR1", "KR2"],
        "China": ["CN1", "CN2", "CN3"],
        "Iran": ["IA1"],
        "Australia": ["AU1", "AU2V", "AU2NSW", "AU2S", "AU2W"],
        "Saudi-Arabia": ["SA1", "SA2"],
        "Thailand": ["TH1"],
        "Qatar": ["QA1", "QA2"],
        "United Arab Emirates": ["AE1"],
        "Indonesia": ["ID1"],
        "Jordan": ["JO1"],
        "Malaysia": ["MY1"],
        "Vietnam": ["VN1"],
        "Kuwait": ["KW1"],
        "Bahrain": ["BH1"],
        "India": ["IN1", "IN2"],
        "Hong Kong": ["HK1"],
        "Singapore": ["SG1"],
        "Bangladesh": ["BD1"],
        "Egypt": ["EG1"],
        "Morocco": ["MA1"],
        "South-Africa": ["ZA1", "ZA2"],
        "Rwanda": ["RW1"],
    },
    "Women's": {
        "England-Women": ["UW1", "UW2"],
        "Spain-Women": ["EW1", "EW2"],
        "Germany-Women": ["GW1", "GW2"],
        "Brazil-Women": ["FB1"],
        "France-Women": ["FF1"],
        "Italy-Women": ["IF1"],
        "Sweden-Women": ["SX1", "SX2"],
        "Norway-Women": ["NW1", "NW2"],
        "Iceland-Women": ["IW1"],
        "Scotland-Women": ["SP1"],
        "Netherlands-Women": ["NV1"],
        "Japan-Women": ["JW1", "JW2"],
        "Finland-Women": ["FW1"],
        "Mexico-Women": ["MF1"],
        "Czech-Republic-Women": ["LZ1"],
        "USA-Women": ["UV1", "UV2"],
        "Australia-Women": ["AW1"],
        "South-Korea-Women": ["KX1"],
    },
}
